In [86]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/elangoparamasivam/credit/creditcard.csv
/kaggle/input/datasets/elangoparamasivam/ccfraud/creditcard1.csv


In [87]:
import pandas as pd


In [88]:
df = pd.read_csv("/kaggle/input/datasets/elangoparamasivam/ccfraud/creditcard1.csv")
print(df.head())

   Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28 

In [89]:
print(df.shape)

(284807, 31)


In [90]:
print(df.info)

<bound method DataFrame.info of             Time         V1         V2        V3        V4        V5  \
0            0.0  -1.359807  -0.072781  2.536347  1.378155 -0.338321   
1            0.0   1.191857   0.266151  0.166480  0.448154  0.060018   
2            1.0  -1.358354  -1.340163  1.773209  0.379780 -0.503198   
3            1.0  -0.966272  -0.185226  1.792993 -0.863291 -0.010309   
4            2.0  -1.158233   0.877737  1.548718  0.403034 -0.407193   
...          ...        ...        ...       ...       ...       ...   
284802  172786.0 -11.881118  10.071785 -9.834783 -2.066656 -5.364473   
284803  172787.0  -0.732789  -0.055080  2.035030 -0.738589  0.868229   
284804  172788.0   1.919565  -0.301254 -3.249640 -0.557828  2.630515   
284805  172788.0  -0.240440   0.530483  0.702510  0.689799 -0.377961   
284806  172792.0  -0.533413  -0.189733  0.703337 -0.506271 -0.012546   

              V6        V7        V8        V9  ...       V21       V22  \
0       0.462388  0.239599  

In [91]:
print(df.isnull().sum())

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64


In [92]:
print(df.columns)

Index(['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
       'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount',
       'Class'],
      dtype='object')


In [93]:
for col in df.columns:
    print(col, df[col].unique()[:5])

Time [0. 1. 2. 4. 7.]
V1 [-1.35980713  1.19185711 -1.35835406 -0.96627171 -1.15823309]
V2 [-0.07278117  0.26615071 -1.34016307 -0.18522601  0.87773675]
V3 [2.53634674 0.16648011 1.77320934 1.79299334 1.54871785]
V4 [ 1.37815522  0.44815408  0.37977959 -0.86329128  0.40303393]
V5 [-0.33832077  0.06001765 -0.50319813 -0.01030888 -0.40719338]
V6 [ 0.46238778 -0.08236081  1.80049938  1.24720317  0.09592146]
V7 [ 0.23959855 -0.07880298  0.79146096  0.23760894  0.59294075]
V8 [ 0.0986979   0.08510165  0.24767579  0.37743587 -0.27053268]
V9 [ 0.36378697 -0.25542513 -1.51465432 -1.38702406  0.81773931]
V10 [ 0.09079417 -0.16697441  0.20764287 -0.05495192  0.75307443]
V11 [-0.55159953  1.61272666  0.62450146 -0.22648726 -0.82284288]
V12 [-0.61780086  1.06523531  0.06608369  0.17822823  0.53819555]
V13 [-0.99138985  0.48909502  0.71729273  0.50775687  1.34585159]
V14 [-0.31116935 -0.1437723  -0.16594592 -0.28792375 -1.11966983]
V15 [ 1.46817697  0.63555809  2.34586495 -0.63141812  0.17512113]
V1

In [94]:
print(df["Class"].value_counts())

Class
0    284315
1       492
Name: count, dtype: int64


In [95]:
print(df.isnull().sum().sum())
print(df[["Time", "Amount"]].describe().round(2))

0
            Time     Amount
count  284807.00  284807.00
mean    94813.86      88.35
std     47488.15     250.12
min         0.00       0.00
25%     54201.50       5.60
50%     84692.00      22.00
75%    139320.50      77.16
max    172792.00   25691.16


In [96]:
from sklearn.preprocessing import StandardScaler

In [97]:
scaler = StandardScaler()
df["Amount_scaled"] = scaler.fit_transform(df[["Amount"]])
df = df.drop(columns = ["Time", "Amount"])
print(df.shape)
print(df.head())



(284807, 30)
         V1        V2        V3        V4        V5        V6        V7  \
0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9       V10  ...       V21       V22       V23       V24  \
0  0.098698  0.363787  0.090794  ... -0.018307  0.277838 -0.110474  0.066928   
1  0.085102 -0.255425 -0.166974  ... -0.225775 -0.638672  0.101288 -0.339846   
2  0.247676 -1.514654  0.207643  ...  0.247998  0.771679  0.909412 -0.689281   
3  0.377436 -1.387024 -0.054952  ... -0.108300  0.005274 -0.190321 -1.175575   
4 -0.270533  0.817739  0.753074  ... -0.009431  0.798278 -0.137458  0.141267   

        V25       V26       V27       V28  Class  Amoun

In [98]:
print(df.columns.tolist())

['V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Class', 'Amount_scaled']


In [99]:
from sklearn.model_selection import train_test_split

In [100]:
X = df.drop(columns = ["Class"])
y = df["Class"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42, stratify = y )

print("Training set :", X_train.shape)
print("Testing set :", X_test.shape)
print("Fraud test:", y_test.sum())

Training set : (227845, 29)
Testing set : (56962, 29)
Fraud test: 98


In [101]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [102]:
model = RandomForestClassifier(n_estimators = 100, random_state = 42, n_jobs = -1)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[56859     5]
 [   17    81]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.94      0.83      0.88        98

    accuracy                           1.00     56962
   macro avg       0.97      0.91      0.94     56962
weighted avg       1.00      1.00      1.00     56962



In [103]:
model2 = RandomForestClassifier(n_estimators = 100, random_state = 42,
                                n_jobs = -1, class_weight = "balanced")
model2.fit(X_train, y_train)

y_pred2 = model2.predict(X_test)

print(confusion_matrix(y_test, y_pred2))
print(classification_report(y_test, y_pred2))

[[56861     3]
 [   24    74]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.96      0.76      0.85        98

    accuracy                           1.00     56962
   macro avg       0.98      0.88      0.92     56962
weighted avg       1.00      1.00      1.00     56962



In [104]:
from imblearn.over_sampling import SMOTE

In [110]:
smote = SMOTE(random_state = 42)

X_resampled, y_resampled = smote.fit_resample(X_train, y_train)

print("Before smote: ", y_train.value_counts().to_dict())
print("After smote: ", y_resampled.value_counts().to_dict())

Before smote:  {0: 227451, 1: 394}
After smote:  {0: 227451, 1: 227451}


In [111]:
model3 = RandomForestClassifier(n_estimators = 100, random_state = 42,
                                n_jobs = -1)
model3.fit(X_resampled, y_resampled)

y_pred3 = model3.predict(X_test)

print(confusion_matrix(y_test, y_pred3))
print(classification_report(y_test, y_pred3))

[[56852    12]
 [   17    81]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.87      0.83      0.85        98

    accuracy                           1.00     56962
   macro avg       0.94      0.91      0.92     56962
weighted avg       1.00      1.00      1.00     56962



In [114]:
from xgboost import XGBClassifier

In [118]:
model4 = XGBClassifier(n_estimaters = 100, random_state = 42,
                       scale_pos_weight=len(y_train[y_train == 0]) / len(y_train[y_train == 1]),
                      eval_metric = "aucpr")
model4.fit(X_train, y_train)
y_pred4 = model4.predict(X_test)

print(confusion_matrix(y_test, y_pred4))
print(classification_report(y_test, y_pred4))


/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:10:30] WARNING: /__w/xgboost/xgboost/src/learner.cc:782: 
Parameters: { "n_estimaters" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


[[56853    11]
 [   15    83]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.88      0.85      0.86        98

    accuracy                           1.00     56962
   macro avg       0.94      0.92      0.93     56962
weighted avg       1.00      1.00      1.00     56962

